add changes to test with new version

diff --git a/.github/workflows/mergebuild.yml b/.github/workflows/mergebuild.yml
--- a/.github/workflows/mergebuild.yml
+++ b/.github/workflows/mergebuild.yml
@@ -95,64 +95,33 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-2
         
-      - name: Get Existing Launch Template ID
-        id: get-launch-template-id
+      - name: New Launch Template Version & ASG Refresh
         run: |
-          # List all Launch Templates and extract the first one (you may adjust the logic as needed)
-          TEMPLATE_ID=$(aws ec2 describe-launch-templates --query 'LaunchTemplates[0].LaunchTemplateId' --output text)
-          echo "::set-output name=template-id::$TEMPLATE_ID"
-        env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_DEFAULT_REGION: us-east-2
-        
-      - name: Update Launch Template
-        run: |
-            TEMPLATE_ID="${{ steps.get-launch-template-id.outputs.template-id }}"
-            CURRENT_VERSION="${{ steps.get-current-template-version.outputs.current-version }}"
-            aws ec2 create-launch-template-version \
-            --launch-template-id $(aws ec2 describe-launch-templates \
-                                    --query 'sort_by(LaunchTemplates, &CreateTime)[-1].LaunchTemplateId' \
-                                    --output text) \
-            --version-description Update-Launch-Template \
-            --source-version 1 \
-            --launch-template-data "ImageId=$AMI_ID"
-        env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_DEFAULT_REGION: us-east-2
-          
-      - name: Update Auto Scaling Group with Latest Launch Template Version
-        run: |
-
-            TEMPLATE_ID="${{ steps.get-launch-template-id.outputs.template-id }}"
-
-            DEFAULT_ASG_NAME=$(aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[0].AutoScalingGroupName' --output text)
-            echo "Default ASG Name is $DEFAULT_ASG_NAME"
-            LATEST_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-id "$TEMPLATE_ID" --query 'LaunchTemplateVersions | sort_by(@, &VersionNumber) | [-1].VersionNumber' --output text)
-
-            # Update the Auto Scaling Group to use the latest Launch Template version
-            aws autoscaling update-auto-scaling-group --auto-scaling-group-name $DEFAULT_ASG_NAME --launch-template "LaunchTemplateId=$TEMPLATE_ID,Version=$LATEST_VERSION"
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: us-east-2
-
-      - name: Start instance refresh
-        run: |
-          aws autoscaling start-instance-refresh \
-          --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups \
-          --query "AutoScalingGroups[0].AutoScalingGroupName" \
-          --output text)\
-              ]
-
-          while [[ "$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text) --query 'InstanceRefreshes[0].Status' --output text)" != "Successful" ]]; do
-            echo "Waiting for instance refresh to complete..."
-            sleep 30
-          done
-
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: us-east-2
-
+            if ! [[ $launch_template_id == null ]] && ! [[ $auto_scaling_name == null ]]
+            then
+              echo "Launch Template Found"
+    
+              aws ec2 create-launch-template-version \
+                --launch-template-id $(aws ec2 describe-launch-templates \
+                                        --query 'sort_by(LaunchTemplates, &CreateTime)[-1].LaunchTemplateId' \
+                                        --output text) \
+                --version-description Version2 \
+                --source-version 1 \
+                --launch-template-data "ImageId=$(aws ec2 describe-images \
+                                                    --owners ${{ secrets.AMI_OWNER_ID}} \
+                                                    --query 'sort_by(Images, &CreationDate)[-1].ImageId' \
+                                                    --output text)"
+              
+              aws autoscaling start-instance-refresh \
+                --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups \
+                                              --query "AutoScalingGroups[0].AutoScalingGroupName" \
+                                              --output text)
+                
+            else
+              echo "Launch Template Not Found"
+            fi
+    
+            while [[ "$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $(aws autoscaling describe-auto-scaling-groups --query "AutoScalingGroups[0].AutoScalingGroupName" --output text) --query 'InstanceRefreshes[0].Status' --output text)" != "Successful" ]]; do
+              echo "Waiting for instance refresh to complete..."
+              sleep 30
+            done
